# Generated by Django 2.2.7 on 2019-12-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='bsns_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
