# Generated by Django 2.2.7 on 2019-12-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itk_app', '0002_auto_20191202_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
