# Generated by Django 2.2.7 on 2019-12-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itk_app', '0003_auto_20191202_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
