# Generated by Django 2.2.7 on 2019-12-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itk_app', '0005_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='description',
            new_name='notice_details',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='title',
            new_name='notice_title',
        ),
    ]
