# Generated by Django 2.2.7 on 2019-12-02 14:21

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('itk_app', '0007_notice_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('tel', phone_field.models.PhoneField(blank=True, help_text='Police Station Phone Number', max_length=31)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itk_app.Neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('tel', phone_field.models.PhoneField(blank=True, help_text='Hospital Phone Number', max_length=31)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itk_app.Neighborhood')),
            ],
        ),
    ]
