# Generated by Django 2.2.7 on 2019-12-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itk_app', '0009_neighborhood_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='population',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
