# Generated by Django 2.2.7 on 2019-12-03 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itk_app', '0013_auto_20191203_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itk_app.Neighborhood'),
        ),
    ]
