# Generated by Django 2.2.7 on 2019-12-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itk_app', '0014_notice_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighborhood',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='itk_app.Neighborhood'),
        ),
    ]
